# Generated by Django 3.0.5 on 2020-07-12 01:37

from django.db import migrations


def copy_src_to_dst(Source, Destination):
    '''
    Para cada ABC, Instanciar um MTI com todos os atributos
    salvar o MTI
    associar os speakers do ABC no MTI
    deletar o ABC
    '''

    # logica
    for src in Source.objects.all():
        dst = Destination(
            title=src.title,
            start=src.start,
            description=src.description,
            slots=src.slots)

        # salvando
        dst.save()

        # associano o speakers ao novo Course. definino q os speakers do MTI é o mesmo do ABC
        dst.speakers.set(src.speakers.all())

        # Deletando o ABC
        src.delete()


def forward_course_abc_to_mti(apps, schema_editor):
    copy_src_to_dst(
        apps.get_model('core', 'CourseOld'),
        apps.get_model('core', 'Course')
    )


def backward_course_abc_to_mti(apps, schema_editor):
    copy_src_to_dst(
        apps.get_model('core', 'CourseOld'),
        apps.get_model('core', 'Course')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_course'),
    ]

    operations = [
        migrations.RunPython(forward_course_abc_to_mti,
                             backward_course_abc_to_mti)
    ]
